spring:
  application:
    name: MeetingBot
  datasource:
    url: jdbc:mariadb://localhost:3306/discordclubbot
    username: ${DB_USER:meetingbot}
    password: ${DB_PASSWORD:sdcs2024}
    driver-class-name: org.mariadb.jdbc.Driver
  discord:
    token: ${DISCORD_TOKEN}
    server-id: ${DISCORD_SERVER_ID}
    officer-channel-id: ${DISCORD_CHANNEL_ID}
    zone-id: ${ZONE_ID:America/Los_Angeles}
    scheduling: 0 0 9 * * ?
    self-nomination:
      img-url: https://i.imgflip.com/1hhv9m.jpg?a478296
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    club.sdcs: DEBUG