spring:
  application:
    name: DiscordClubBot
  datasource:
    url: jdbc:h2:file:./sdcs;DB_CLOSE_ON_EXIT=FALSE;
    username: ${DB_USER:sdcs}
    password: ${DB_PASSWORD:sdcs2024}
    driver-class-name: org.h2.Driver
  discord:
    token: ${DISCORD_TOKEN}
    server-id: ${DISCORD_SERVER_ID}
  h2:
    console:
      enabled: true
    port: 9092
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # once db schema is stabilized, switch to update and use flyway to version schema
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    club.sdcs: DEBUG