spring:
  application:
    name: MembershipBot
  datasource:
    url: jdbc:mariadb://localhost:3306/discordclubbot
    username: ${DB_USER:membershipbot}
    password: ${DB_PASSWORD:sdcs2024}
    driver-class-name: org.mariadb.jdbc.Driver
  discord:
    token: ${DISCORD_TOKEN}
    server-id: ${DISCORD_SERVER_ID}
    active:
      condition:
        num-meetings-attended: 1
        in-past-num-days: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    club.sdcs: DEBUG