spring:
  application:
    name: DiscordClubBot
  datasource:
    url: jdbc:h2:file:./sdcs;AUTO_SERVER=TRUE;
    username: ${DB_USER:sdcs}
    password: ${DB_PASSWORD:sdcs2024}
    driver-class-name: org.h2.Driver
  discord:
    token: ${DISCORD_TOKEN}
    server-id: ${DISCORD_SERVER_ID}
    officer-channel-id: ${DISCORD_CHANNEL_ID}
    zone-id: ${ZONE_ID:America/Los_Angeles}
    scheduling: 0 0 9 * * ?
    active:
      check:
        schedule: 0 0 9 * * ?
      condition:
        num-meetings-attended: 1
        in-past-num-days: 30
    self-nomination:
      img-url: https://upload.wikimedia.org/wikipedia/commons/4/42/Shrug.jpg
  h2:
    console:
      enabled: true
    port: 9092
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # once db schema is stabilized, switch to update and use flyway to version schema
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    club.sdcs: DEBUG